---

_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

#The Python Programming Language: Variables

Variables are a storage placeholder for text and numbers. They must have a name in order to access them.

A variable is always assigned with the equal sign, followed by the variable value.

In [0]:
x = 1

There are different types of variables in Python, in order to contain different types of data (numbers, text, sets, files)

In [0]:
x = 1
y = 'Hello World'
z = 3.14

In [0]:
x

In [0]:
y

In [0]:
z

**Task:** 
Create a variable called *firstVariable*, and assign it a value of 5

Create a variable called *secondVariable*, and assign it a value of 10

Calculate the sum, difference, product and division, saving the values on a variable of each name

Show all the values

# The Python Programming Language: Functions

In [0]:
x = 1
y = 2
x + y

In [0]:
x

<br>
`add_numbers` is a function that takes two numbers and adds them together.

In [0]:
def add_numbers(x, y):
    return x + y

add_numbers(1, 2)

<br>
`add_numbers` updated to take an optional 3rd parameter. Using `print` allows printing of multiple expressions within a single cell.

In [0]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

<br>
`add_numbers` updated to take an optional flag parameter.

In [0]:
def add_numbers(x, y, z=None, flag=False):
    if (flag):
        print('Flag is true!')
    if (z==None):
        return x + y
    else:
        return x + y + z
    
print(add_numbers(1, 2, flag=True))

<br>
Assign function `add_numbers` to variable `a`.

In [0]:
def add_numbers(x,y):
    return x+y

a = add_numbers
a(1,2)

**Task:**

Repeat the previous task using functions to implement the calculations implementing 4 functions.

**Task:**

Implement a function that receives 2 parameters: a number and a string.

If the string is 'sum', return the number plus 2

If the string is 'substract', return the number minus 2

If the string is 'multiply', return the number times 2

If the string is 'divide', return the number divided by 2

<br>
# The Python Programming Language: Types and Sequences

<br>
Use `type` to return the object's type.

In [0]:
type('This is a string')

In [0]:
type(None)

In [0]:
type(1)

In [0]:
type(1.0)

In [0]:
type(add_numbers)

<br>
Tuples are an immutable data structure (cannot be altered).

In [0]:
x = (1, 'a', 2, 'b')
type(x)

<br>
Lists are a mutable data structure.

In [0]:
x = [1, 'a', 2, 'b']
type(x)

<br>
Use `append` to append an object to a list.

In [0]:
x.append(3.3)
print(x)

<br>
This is an example of how to loop through each item in the list.

In [0]:
for item in x:
    print(item)

<br>
Or using the indexing operator:

In [0]:
i=0
while( i != len(x) ):
    print(x[i])
    i = i + 1

<br>
Use `+` to concatenate lists.

In [0]:
[1,2] + [3,4]

<br>
Use `*` to repeat lists.

In [0]:
[1]*3

<br>
Use the `in` operator to check if something is inside a list.

In [0]:
1 in [1, 2, 3]

**Task:**

Generate a list with the number from 0 to 10

Show all the numbers using a for loop

**Task:**

Concatenate two lists (one with numbers from 1 to 5, and the second from 6 to 10) to get the same list as before

Show all the numbers using a for loop

**Task:**

Implement a function that receives a list of numbers, and calculates the average of all the numbers.

**Task:**

Implement a function that returns True if the number 5 is inside it. And False otherwise.

<br>
## Strings



Now let's look at strings. 

Strings can be seen as lists of characters.

Use bracket notation to slice a string.

In [0]:
x = 'This is a string'
print(x[0]) #first character
print(x[0:1]) #first character, but we have explicitly set the end character
print(x[0:2]) #first two characters

<br>
This will return the last element of the string.

In [0]:
x[-1]

<br>
This will return the slice starting from the 4th element from the end and stopping before the 2nd element from the end.

In [0]:
x[-4:-2]

<br>
This is a slice from the beginning of the string and stopping before the 3rd element.

In [0]:
x[:3]

<br>
And this is a slice starting from the 3rd element of the string and going all the way to the end.

In [0]:
x[3:]

In [0]:
firstname = 'John'
lastname = 'Doe'

print(firstname + ' ' + lastname)
print(firstname*3)
print('Chris' in firstname)

<br>
`split` returns a list of all the words in a string, or a list split on a specific character.

In [0]:
firstname = 'John Arthur Hansen Doe'.split(' ')[0] # [0] selects the first element of the list
lastname = 'John Arthur Hansen Doe'.split(' ')[-1] # [-1] selects the last element of the list
print(firstname)
print(lastname)

<br>
Make sure you convert objects to strings before concatenating, because all the variables should the same type when doing it.

In [0]:
'John' + 2

In [0]:
'John' + str(2)

**Task:**

Set a variable with your first name, and your last name.

Set a variable with your complete name.

Show your complete name.

**Task:**

Set a variable with the first three letters of your first name, and the three first letters of your last name, using the variables from the previous task.

**Task:**

Get the first and the third name of the *strangeName* variable, and show them.

In [0]:
strangeName = 'Ilyena Lydia Vasilievna Mironov'

<br>
## Dictionaries

Dictionaries associate keys with values.

In [0]:
x = {'John Doe': 'jdoe@mail.com', 'Bill Gates': 'billg@microsoft.com'}
x['John Doe'] # Retrieve a value by using the indexing operator

In [0]:
x['Kevyn Collins-Thompson'] = None
x['Kevyn Collins-Thompson']

<br>
Iterate over all of the keys:

In [0]:
for name in x:
    print(x[name])

<br>
Iterate over all of the values:

In [0]:
for email in x.values():
    print(email)

<br>
Iterate over all of the items in the list:

In [0]:
for name, email in x.items():
    print(name)
    print(email)

<br>
You can unpack a sequence into different variables:

In [0]:
x = ('John', 'Doe', 'jdoe@mail.com')
fname, lname, email = x

In [0]:
fname

In [0]:
lname

<br>
Make sure the number of values you are unpacking matches the number of variables being assigned.

In [0]:
x = ('John', 'Doe', 'jdoe@mail.com', 'Ann Arbor')
fname, lname, email = x

**Task:**

Create a dictionary with 3 entries, the key will be a name, and the value an email.

**Task:**

Create a dictionary with 3 entries, the key will be a name, and the value an array of the projects this person is working right now.

**Task:**

Create a function that, given a name of a person, returns the email set on the previous task.

**Task:**

Create a function that, given a project, returns all the names involved in the project, or 'Nobody' if nobody is involved in the project.

<br>
# Reading and Writing CSV files

<br>
Let's import our datafile mpg.csv, which contains fuel economy data for 234 cars.

* mpg : miles per gallon
* class : car classification
* cty : city mpg
* cyl : # of cylinders
* displ : engine displacement in liters
* drv : f = front-wheel drive, r = rear wheel drive, 4 = 4wd
* fl : fuel (e = ethanol E85, d = diesel, r = regular, p = premium, c = CNG)
* hwy : highway mpg
* manufacturer : automobile manufacturer
* model : model of car
* trans : type of transmission
* year : model year

In order to import the file, you will need to provide Colab access to your drive files.

Execute the following code, and insert the access token on the input field.

Then navigate to the folder following the

In [0]:
from google.colab import drive
drive.mount('/content/drive')

#TODO: get to the correct folder

In [0]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:3] # The first three dictionaries in our list.

<br>
`csv.Dictreader` has read in each row of our csv file as a dictionary. `len` shows that our list is comprised of 234 dictionaries.

In [0]:
len(mpg)

<br>
`keys` gives us the column names of our csv.

In [0]:
mpg[0].keys()

<br>
This is how to find the average cty fuel economy across all cars. All values in the dictionaries are strings, so we need to convert to float.

In [0]:
sum(float(d['cty']) for d in mpg) / len(mpg)

<br>
Similarly this is how to find the average hwy fuel economy across all cars.

In [0]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

<br>
Use `set` to return the unique values for the number of cylinders the cars in our dataset have.

In [0]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

<br>
Here's a more complex example where we are grouping the cars by number of cylinder, and finding the average cty mpg for each group.

In [0]:
CtyMpgByCyl = []

for c in cylinders: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterate over all dictionaries
        if d['cyl'] == c: # if the cylinder level type matches,
            summpg += float(d['cty']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CtyMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')

CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

<br>
Use `set` to return the unique values for the class types in our dataset.

In [0]:
vehicleclass = set(d['class'] for d in mpg) # what are the class types
vehicleclass

<br>
And here's an example of how to find the average hwy mpg for each class of vehicle in our dataset.

In [0]:
HwyMpgByClass = []

for t in vehicleclass: # iterate over all the vehicle classes
    summpg = 0
    vclasscount = 0
    for d in mpg: # iterate over all dictionaries
        if d['class'] == t: # if the cylinder amount type matches,
            summpg += float(d['hwy']) # add the hwy mpg
            vclasscount += 1 # increment the count
    HwyMpgByClass.append((t, summpg / vclasscount)) # append the tuple ('class', 'avg mpg')

HwyMpgByClass.sort(key=lambda x: x[1])
HwyMpgByClass

**Task:**

Find the amount of cars for each type of transmision

<br>
# The Python Programming Language: Dates and Times

In [0]:
import datetime as dt
import time as tm

<br>
`time` returns the current time in seconds since the Epoch. (January 1st, 1970)

In [0]:
tm.time()

<br>
Convert the timestamp to datetime.

In [0]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

Using datetime it is possible to define a variable with a certain date:

In [0]:
moonLanding = dt.date(1969, 7, 20)

moonLanding.strftime('%x')

<br>
Handy datetime attributes:

In [0]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

<br>
`timedelta` is a duration expressing the difference between two dates.

In [0]:
delta = dt.timedelta(days = 100) # create a timedelta of 100 days
delta

<br>
`date.today` returns the current local date.

In [0]:
today = dt.date.today()

In [0]:
today - delta # the date 100 days ago

In [0]:
today > today-delta # compare dates

**Task:**

Find the amount of days passed today from the day you were born.

<br>
# The Python Programming Language: Numerical Python (NumPy)

In [0]:
import numpy as np

<br>
## Creating Arrays

Create a list and convert it to a numpy array

In [0]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

<br>
Or just pass in a list directly

In [0]:
y = np.array([4, 5, 6])
y

<br>
Pass in a list of lists to create a multidimensional array.

In [0]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

<br>
Use the shape method to find the dimensions of the array. (rows, columns)

In [0]:
m.shape

<br>
`arange` returns evenly spaced values within a given interval.

In [0]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

<br>
`reshape` returns an array with the same data with a new shape.

In [0]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

<br>
#### Combining Arrays

In [0]:
p = np.ones([2, 3], int)
p

<br>
Use `vstack` to stack arrays in sequence horizontally (column wise).

In [0]:
np.vstack([p, 2*p])

<br>
Use `hstack` to stack arrays in sequence horizontally (column wise).

In [0]:
np.hstack([p, 2*p])

**Task:**

Set up an array that counts from 0 to 100 in steps of 5

**Task:**

Set the previous array a shape of 4 columns and 5 rows

<br>
## Operations

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [0]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

In [0]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

In [0]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [0]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

In [0]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array

**Task:**

Set an array with all the number from 0 to 10, and another with numbers from 10 to 0.

Show the results of adding, substracting, multiplying, and applying the dot product to them.

<br>
## Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [0]:
a = np.array([-4, -2, 1, 3, 5])

In [0]:
a.sum()

In [0]:
a.max()

In [0]:
a.min()

In [0]:
a.mean()

In [0]:
a.std()

<br>
`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [0]:
a.argmax()

In [0]:
a.argmin()

<br>
## Indexing / Slicing

In [0]:
s = np.arange(13)**2
s

<br>
Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

In [0]:
s[0], s[4], s[-1]

<br>
Use `:` to indicate a range. `array[start:stop]`


Leaving `start` or `stop` empty will default to the beginning/end of the array.

In [0]:
s[1:5]

<br>
Use negatives to count from the back.

In [0]:
s[-4:]

<br>
A second `:` can be used to indicate step-size. `array[start:stop:stepsize]`

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [0]:
s[-5::-2]

<br>
Let's look at a multidimensional array.

In [0]:
r = np.arange(36)
r.resize((6, 6))
r

<br>
Use bracket notation to slice: `array[row, column]`

In [0]:
r[2, 2]

<br>
And use : to select a range of rows or columns

In [0]:
r[3, 3:6]

<br>
Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [0]:
r[:2, :-1]

<br>
This is a slice of the last row, and only every other element.

In [0]:
r[-1, ::2]

<br>
We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [0]:
r[r > 30]

<br>
Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [0]:
r[r > 30] = 30
r

<br>
## Copying Data

Be careful with copying and modifying arrays in NumPy!


`r2` is a slice of `r`

In [0]:
r2 = r[:3,:3]
r2

<br>
Set this slice's values to zero ([:] selects the entire array)

In [0]:
r2[:] = 0
r2

<br>
`r` has also been changed!

In [0]:
r

<br>
To avoid this, use `r.copy` to create a copy that will not affect the original array

In [0]:
r_copy = r.copy()
r_copy

<br>
Now when r_copy is modified, r will not be changed.

In [0]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

**Task:**

You are given an array of random numbers, get:

the maximum number

the minimum number

the mean of the numbers

the standard deviation

the last row of the matrix

the fifth row of the matrix

Copy it in a new array

In this new array, set all numbers above 50 to 100

Show both arrays

In [0]:
randomNumbers = np.random.rand(10, 10) * 100

randomNumbers